name: 'JFrog CLI'
description: 'Execute JFrog CLI'
author: 'JFrog'
inputs:
    version:
        description: 'JFrog CLI Version'
        default: '1.29.0'
        required: false
runs:
    using: 'node12'
    main: 'lib/main.js'
