name: "Setup JFrog CLI"
description: "Install and configure JFrog CLI."
author: "JFrog"
inputs:
    version:
        description: "JFrog CLI Version"
        default: "2.68.0"
        required: false
    download-repository:
        description: "Remote repository in Artifactory pointing to 'https://releases.jfrog.io/artifactory/jfrog-cli'. Use this parameter in case you don't have an Internet access."
        required: false
    oidc-provider-name:
        description: "Provider Name's value that was set in OpenId Connect integration in the JFrog platform."
        required: false
    oidc-audience:
        description: "By default, this is the URL of the GitHub repository owner, such as the organization that owns the repository."
        required: false
    disable-job-summary:
        description: "Set to true to disable the generation of Job Summaries."
        default: "false"
        required: false
    disable-auto-build-publish:
        description: "By default, if the workflow completes with collected build-info that has not been published using the jf rt build-publish command, the build-info will be automatically published to Artifactory. Set this to true to disable the automatic publication of build-info at the end of the workflow."
        default: "false"
        required: false
outputs:
    oidc-token:
        description: "JFrog OIDC token generated by the Setup JFrog CLI when setting oidc-provider-name."
    oidc-user:
        description: "JFrog OIDC username from the OIDC token generated by the Setup JFrog CLI when setting oidc-provider-name."
runs:
    using: "node20"
    main: "lib/main.js"
    post: "lib/cleanup.js"
branding:
    icon: "terminal"
    color: "green"
