name: "Setup JFrog CLI"
description: "Install and configure JFrog CLI."
author: "JFrog"
inputs:
    version:
        description: "JFrog CLI Version"
        default: "2.52.9"
        required: false
    download-repository:
        description: "Remote repository in Artifactory pointing to 'https://releases.jfrog.io/artifactory/jfrog-cli'. Use this parameter in case you don't have an Internet access."
        required: false
    oidc-audience:
        description: "Recipient for which the JWT is intended. By default it contains the URL to the repository owner."
        required: false
    oidc-provider-name:
        description: "Provider Name's value that was set in OpenId Connect integration."
        required: false

runs:
    using: "node16"
    main: "lib/main.js"
    post: "lib/cleanup.js"
branding:
    icon: "terminal"
    color: "green"
