name: 'Release'
on:
    release:
        types: published

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v1
            - name: Install
              run: npm i
            - name: Update version
              run: echo ${{ github.ref }} | cut -c 11- | xargs npm version --no-git-tag-version
            - name: Push changes
              uses: ad-m/github-push-action@master
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
